config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts, only: [:index, :destroy, :show]
  resources :comments, only: [:new, :index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many  :comments, dependent: :destroy
  validates :title, :content, :url, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many  :posts, dependent: :destroy
  has_many  :comments, dependent: :destroy
  validates :nickname, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def new
  @comment = Comment.new
end


def create
  #@post = Post.find(params[:post_id])
  @comment = Comment.new(comment_params)
  @comment.post_id = "1"
  @comment.user = current_user

  if @comment.save
     redirect_to posts_path
  else
    render :new, status: :unprocessable_entity
    # raise
  end
  puts("Hello")
end

private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :post_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  # Refactor: Mise en commun d'une partie du code

  def index
    @posts = Post.all
  end

  def show
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :url, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<div class="container">
  <%= simple_form_for comment do |f| %>
    <%= f.input :content, as: :text %>
    <br>
    <h3>Valider votre commentaire</h3>
    <br>
    <br>
    <span><%= f.submit %></span>
   <% end %>
</div>

app/views/comments/new.html.erb
<div class="container new-container">
  <h1>Ajouter un avis</h1>

  <%= render "form", comment: @comment %>

  <br>
  <%= link_to "Retour à la page d'acceuil", posts_path  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsArticleComment</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dv8dkbyra/image/upload/v1671413563/nasa-Q1p7bh3SHj8-unsplash_upsgnm.jpg);">
  <div class="container">
    <h1>S'informer sur les innovations dand le monde de la <strong>High Tech</strong> !</h1>
    <p>Les nouvelles du Monde Informatique</p>
    <p><span data-controller="typed-js"></span></p>
  </div>
</div>
<br>
<br>
  <ul>
    <% @posts.each do |post|  %>
      <% if post.title ==  "Les consommateurs américains inquiets de l'exploitation de leurs données personnelles" %>
        <%= image = "e1mwaajrjnlgqoqnotdp" %>
        <% elsif post.title == "Les pénuries de composants sont en phase de résolution" %>
          <%= image = "adi-goldstein-EUsVwEOsblE-unsplash_rfkn1w" %>
        <% elsif post.title == "Le Zero Trust, un modèle à explorer" %>%
          <%= image ="brooke-cagle-g1Kr4Ozfoac-unsplash_vh5n58" %>
        <% else %>
          <%= image = "luca-bravo-XJXWbfSo2f0-unsplash_dwndza" %>
      <% end %>
      <li>
        <div class="card-product">
          <%= cl_image_tag image, alt: "alttext", width: 300, height: 300, crop: :fill %>
          <div class="card-product-infos">
            <div>
              <h2><%=post.title %></h2>
              <h3><%=post.content %></h3>
            </div>

            <%= link_to posts_path(post) do %>
              <h4><%=post.url %></h4>
              <a>
              <br>
              <%= link_to "Publier votre commentaire", new_comment_path, class: "btn btn-gradient" %>
              </a>
              <br>
            <% end %>
          </div>
          <cr>
        </div>
      </li>
    <% end  %>
  </ul>
  <br>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://picsum.photos/id/237/400/400", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>